branches:
  only:
    - master
language: node_js
node_js:
- lts/*
git: 
  depth: 3
install:
- yarn --frozen-lockfile
script:
- yarn build
cache: yarn
deploy:
- provider: pages
  local-dir: examples/dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
- provider: npm
  email: lipeizhao318@gmail.com
  api_key: $NPM_TOKEN
  skip-cleanup: true
